const express = require('express');
const { Pool } = require('pg');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const cookieParser = require('cookie-parser');
const crypto = require('crypto');
const path = require('path');
const fs = require('fs');

const PORT = process.env.PORT || 3000;
const TEACHER_CODE = process.env.TEACHER_CODE || '';
const SECRET = process.env.JWT_SECRET;
if (!process.env.DATABASE_URL) throw new Error('DATABASE_URL не задан в .env');
if (!SECRET) throw new Error('JWT_SECRET не задан в .env');

const db = new Pool({ connectionString: process.env.DATABASE_URL });
db.on('error', error => console.error('Ошибка неактивного соединения с PostgreSQL:', error));
const schema = `
create table if not exists users(
  id integer generated by default as identity primary key,
  login text not null unique,
  name text not null,
  cls text not null default '',
  role text not null default 'student',
  p1 text not null default '',
  p2 text not null default '',
  target integer not null default 100,
  pass_hash text not null,
  created_at timestamptz not null default current_timestamp
);
create table if not exists sessions(
  id integer generated by default as identity primary key,
  d date not null unique
);
create table if not exists results(
  session_id integer not null references sessions(id) on delete cascade,
  user_id integer not null references users(id) on delete cascade,
  h integer not null, m integer not null, r integer not null, a integer not null, b integer not null,
  primary key(session_id, user_id)
);
create table if not exists settings(key text primary key, value text not null);
`;

async function transaction(work) {
  const client = await db.connect();
  try {
    await client.query('begin');
    const result = await work(client);
    await client.query('commit');
    return result;
  } catch (error) {
    await client.query('rollback');
    throw error;
  } finally {
    client.release();
  }
}

const asyncRoute = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);

const app = express();
app.use(express.json({ limit: '50kb' }));
app.use(cookieParser());
// Сайт отдаётся безопасно: наружу уходят только файлы самого сайта,
// но не исходный код, база данных и .env.
const PUB = path.join(__dirname, 'public');
if (fs.existsSync(path.join(PUB, 'index.html'))) {
  app.use(express.static(PUB)); // структура с папкой public
} else {
  // плоская структура (все файлы лежат в корне, как в GitHub-репозитории): отдаём только файлы сайта
  ['index.html', 'app.js', 'style.css', 'theme.js'].forEach(f =>
    app.get('/' + f, (req, res) => res.sendFile(path.join(__dirname, f))));
  app.get('/', (req, res) => res.sendFile(path.join(__dirname, 'index.html')));
}

// ---------- helpers ----------
const fails = new Map(); // ip -> {n, t}
function limited(req, res, next) {
  const now = Date.now(), k = req.ip;
  let f = fails.get(k);
  if (!f || now - f.t > 15 * 60 * 1000) f = { n: 0, t: now };
  if (f.n >= 15) return res.status(429).json({ error: 'Слишком много попыток. Подождите 15 минут.' });
  f.n++; fails.set(k, f);
  next();
}
function setCookie(res, id) {
  const token = jwt.sign({ id }, SECRET, { expiresIn: '7d' });
  res.cookie('token', token, {
    httpOnly: true, sameSite: 'lax', maxAge: 7 * 864e5,
    secure: process.env.NODE_ENV === 'production'
  });
}
const needAuth = asyncRoute(async (req, res, next) => {
  let payload;
  try {
    payload = jwt.verify(req.cookies.token || '', SECRET);
  } catch {
    return res.status(401).json({ error: 'Нужно войти' });
  }
  const result = await db.query('select * from users where id=$1', [payload.id]);
  if (!result.rows[0]) return res.status(401).json({ error: 'Нужно войти' });
  req.user = result.rows[0];
  next();
});
function needTeacher(req, res, next) {
  if (req.user.role !== 'teacher') return res.status(403).json({ error: 'Только для учителей' });
  next();
}
const str = (v, max) => String(v == null ? '' : v).trim().slice(0, max);
const int = (v, min, max) => { const n = Number(v); return Number.isInteger(n) && n >= min && n <= max ? n : null; };
async function threshold() {
  const result = await db.query("select value from settings where key='threshold'");
  return result.rows[0] ? Number(result.rows[0].value) : 50;
}
const TR = { а:'a',ә:'a',б:'b',в:'v',г:'g',ғ:'g',д:'d',е:'e',ё:'e',ж:'zh',з:'z',и:'i',й:'i',і:'i',к:'k',қ:'k',л:'l',м:'m',н:'n',ң:'n',о:'o',ө:'o',п:'p',р:'r',с:'s',т:'t',у:'u',ұ:'u',ү:'u',ф:'f',х:'h',һ:'h',ц:'c',ч:'ch',ш:'sh',щ:'sh',ъ:'',ы:'y',ь:'',э:'e',ю:'yu',я:'ya' };
const translit = t => String(t).toLowerCase().split('').map(c => TR[c] !== undefined ? TR[c] : c).join('').replace(/[^a-z0-9]/g, '');
function loginBase(name) {
  const w = String(name).trim().split(/\s+/);
  return (translit(w[0]) || 'user') + (w[1] ? '.' + translit(w[1]).slice(0, 1) : '');
}
const ABC = 'abcdefghjkmnpqrstuvwxyz23456789';
const makePass = () => Array.from({ length: 8 }, () => ABC[crypto.randomInt(ABC.length)]).join('');

// ---------- auth ----------
// Регистрация открыта только для учителей (нужен код из .env). Учеников создаёт учитель.
app.post('/api/register', limited, asyncRoute(async (req, res) => {
  const b = req.body || {};
  const login = str(b.login, 30).toLowerCase();
  const name = str(b.name, 80), pass = String(b.password || '');
  if (!TEACHER_CODE || b.teacherCode !== TEACHER_CODE) return res.status(403).json({ error: 'Неверный код учителя' });
  if (!/^[a-z0-9._-]{3,30}$/.test(login)) return res.status(400).json({ error: 'Логин: 3–30 символов, латиница, цифры, точка, дефис' });
  if (!name) return res.status(400).json({ error: 'Укажите фамилию и имя' });
  if (pass.length < 6 || pass.length > 100) return res.status(400).json({ error: 'Пароль: минимум 6 символов' });
  try {
    const result = await db.query(
      "insert into users(login,name,cls,role,pass_hash) values($1,$2,'','teacher',$3) returning id",
      [login, name, bcrypt.hashSync(pass, 10)]
    );
    setCookie(res, result.rows[0].id);
  } catch (error) {
    if (error.code === '23505') return res.status(409).json({ error: 'Такой логин уже занят' });
    throw error;
  }
  res.json({ ok: true });
}));

app.post('/api/login', limited, asyncRoute(async (req, res) => {
  const login = str(req.body && req.body.login, 30).toLowerCase();
  const result = await db.query('select * from users where login=$1', [login]);
  const u = result.rows[0];
  if (!u || !bcrypt.compareSync(String((req.body && req.body.password) || ''), u.pass_hash))
    return res.status(401).json({ error: 'Неверный логин или пароль' });
  fails.delete(req.ip);
  setCookie(res, u.id);
  res.json({ ok: true });
}));

app.post('/api/logout', (req, res) => { res.clearCookie('token'); res.json({ ok: true }); });

// ---------- data ----------
app.get('/api/data', needAuth, asyncRoute(async (req, res) => {
  const me = req.user, teacher = me.role === 'teacher';
  const cols = 'id,login,name,cls,p1,p2,target';
  const students = teacher
    ? (await db.query(`select ${cols} from users where role='student' order by name`)).rows
    : (await db.query(`select ${cols} from users where id=$1`, [me.id])).rows;
  const rs = teacher
    ? (await db.query('select session_id,user_id,h,m,r,a,b from results')).rows
    : (await db.query('select session_id,user_id,h,m,r,a,b from results where user_id=$1', [me.id])).rows;
  const by = {};
  rs.forEach(x => (by[x.user_id] = by[x.user_id] || []).push(x));
  students.forEach(s => (s.results = by[s.id] || []));
  const sessions = (await db.query('select id,to_char(d, \'YYYY-MM-DD\') as d from sessions order by d')).rows;
  res.json({ me: { id: me.id, name: me.name, role: me.role }, threshold: await threshold(), sessions, students });
}));

// --- дни тестов (вторник и пятница) ---
app.post('/api/sessions', needAuth, needTeacher, asyncRoute(async (req, res) => {
  const b = req.body || {};
  const ok = v => {
    if (typeof v !== 'string' || !/^\d{4}-\d{2}-\d{2}$/.test(v)) return false;
    const date = new Date(v + 'T00:00:00.000Z');
    return !Number.isNaN(date.getTime()) && date.toISOString().slice(0, 10) === v;
  };
  if (b.d) {
    if (!ok(b.d)) return res.status(400).json({ error: 'Неверная дата' });
    const result = await db.query('insert into sessions(d) values($1) on conflict(d) do nothing', [b.d]);
    return res.json({ ok: true, added: result.rowCount });
  }
  if (!ok(b.from) || !ok(b.to)) return res.status(400).json({ error: 'Укажите даты «с» и «по»' });
  const a = Date.parse(b.from), z = Date.parse(b.to);
  if (z < a || (z - a) / 864e5 > 400) return res.status(400).json({ error: 'Период: не больше 400 дней' });
  const dates = [];
  for (let t = a; t <= z; t += 864e5) {
    const day = new Date(t).getUTCDay();
    if (day === 2 || day === 5) dates.push(new Date(t).toISOString().slice(0, 10));
  }
  const n = await transaction(async client => {
    let added = 0;
    for (const date of dates) {
      const result = await client.query('insert into sessions(d) values($1) on conflict(d) do nothing', [date]);
      added += result.rowCount;
    }
    return added;
  });
  res.json({ ok: true, added: n });
}));

app.delete('/api/sessions/:id', needAuth, needTeacher, asyncRoute(async (req, res) => {
  await db.query('delete from sessions where id=$1', [Number(req.params.id)]);
  res.json({ ok: true });
}));

// --- баллы вносит только учитель ---
app.put('/api/sessions/:id/results', needAuth, needTeacher, asyncRoute(async (req, res) => {
  const sid = Number(req.params.id);
  if (!(await db.query('select 1 from sessions where id=$1', [sid])).rowCount) return res.status(404).json({ error: 'День теста не найден' });
  const rows = Array.isArray(req.body && req.body.rows) ? req.body.rows : [];
  const clean = [];
  for (const r of rows) {
    const uid = Number(r.studentId);
    const student = await db.query("select id,name from users where id=$1 and role='student'", [uid]);
    if (!student.rowCount) continue;
    if (r.blank) { clean.push({ uid, blank: true }); continue; }
    const h = int(r.h, 0, 20), m = int(r.m, 0, 10), rr = int(r.r, 0, 10), a = int(r.a, 0, 50), b = int(r.b, 0, 50);
    if ([h, m, rr, a, b].includes(null)) {
      return res.status(400).json({ error: `${student.rows[0].name}: проверьте баллы (история 0–20, грамотности 0–10, профильные 0–50)` });
    }
    clean.push({ uid, h, m, r: rr, a, b });
  }
  await transaction(async client => {
    for (const c of clean) {
      if (c.blank) {
        await client.query('delete from results where session_id=$1 and user_id=$2', [sid, c.uid]);
      } else {
        await client.query(`insert into results(session_id,user_id,h,m,r,a,b) values($1,$2,$3,$4,$5,$6,$7)
          on conflict(session_id,user_id) do update set h=excluded.h,m=excluded.m,r=excluded.r,a=excluded.a,b=excluded.b`,
        [sid, c.uid, c.h, c.m, c.r, c.a, c.b]);
      }
    }
  });
  res.json({ ok: true, saved: clean.length });
}));

// --- ученики: создаёт и настраивает только учитель ---
async function createStudent(client, row, rounds) {
  const name = str(row.name, 80), cls = str(row.cls, 10);
  const target = int(row.target, 0, 140) ?? 100;
  const base = loginBase(name);
  let login = base, suffix = 1;
  while ((await client.query('select 1 from users where login=$1', [login])).rowCount) login = base + (++suffix);
  const password = makePass();
  await client.query("insert into users(login,name,cls,role,p1,p2,target,pass_hash) values($1,$2,$3,'student',$4,$5,$6,$7)",
    [login, name, cls, str(row.p1, 40), str(row.p2, 40), target, bcrypt.hashSync(password, rounds)]);
  return { name, cls, p1: str(row.p1, 40), p2: str(row.p2, 40), login, password };
}
app.post('/api/students/bulk', needAuth, needTeacher, asyncRoute(async (req, res) => {
  const rows = Array.isArray(req.body && req.body.rows) ? req.body.rows : [];
  if (!rows.length) return res.status(400).json({ error: 'Список пуст' });
  if (rows.length > 150) return res.status(400).json({ error: 'За один раз можно добавить до 150 учеников' });
  for (let i = 0; i < rows.length; i++)
    if (!rows[i] || !str(rows[i].name, 80) || !str(rows[i].cls, 10)) return res.status(400).json({ error: `Строка ${i + 1}: нужны фамилия, имя и класс` });
  for (let i = 0; i < rows.length; i++)
    if (rows[i].target !== undefined && int(rows[i].target, 0, 140) === null) return res.status(400).json({ error: `Строка ${i + 1}: цель должна быть числом от 0 до 140` });
  const out = [];
  await transaction(async client => {
    for (const row of rows) out.push(await createStudent(client, row, 8));
  });
  res.json({ ok: true, created: out });
}));

app.patch('/api/students/:id', needAuth, needTeacher, asyncRoute(async (req, res) => {
  const id = Number(req.params.id), b = req.body || {};
  const values = [], sets = [];
  if (b.target !== undefined) {
    const target = int(b.target, 0, 140);
    if (target === null) return res.status(400).json({ error: 'Цель: число от 0 до 140' });
    values.push(target);
    sets.push(`target=$${values.length}`);
  }
  if (b.name !== undefined || b.cls !== undefined) {
    const name = str(b.name, 80), cls = str(b.cls, 10);
    if (!name || !cls) return res.status(400).json({ error: 'Фамилия и класс не могут быть пустыми' });
    values.push(name, cls, str(b.p1, 40), str(b.p2, 40));
    sets.push(`name=$${values.length - 3}`, `cls=$${values.length - 2}`, `p1=$${values.length - 1}`, `p2=$${values.length}`);
  }
  if (!sets.length) return res.status(400).json({ error: 'Нет данных для изменения' });
  values.push(id);
  const result = await db.query(`update users set ${sets.join(', ')} where id=$${values.length} and role='student'`, values);
  if (!result.rowCount) return res.status(404).json({ error: 'Ученик не найден' });
  res.json({ ok: true });
}));

// --- новые пароли (старые хранятся только в зашифрованном виде, посмотреть их нельзя) ---
async function newPassword(client, id, rounds) {
  const found = await client.query("select id,login,name,cls from users where id=$1 and role='student'", [id]);
  const u = found.rows[0];
  if (!u) return null;
  const password = makePass();
  await client.query('update users set pass_hash=$1 where id=$2', [bcrypt.hashSync(password, rounds), id]);
  return { name: u.name, cls: u.cls, login: u.login, password };
}
app.post('/api/students/newpass-bulk', needAuth, needTeacher, asyncRoute(async (req, res) => {
  const ids = Array.isArray(req.body && req.body.ids) ? req.body.ids.map(Number) : [];
  if (!ids.length) return res.status(400).json({ error: 'Список пуст' });
  if (ids.length > 150) return res.status(400).json({ error: 'За один раз можно до 150 учеников' });
  const out = [];
  await transaction(async client => {
    for (const id of ids) {
      const result = await newPassword(client, id, 8);
      if (result) out.push(result);
    }
  });
  res.json({ ok: true, created: out });
}));
app.post('/api/students/:id/newpass', needAuth, needTeacher, asyncRoute(async (req, res) => {
  const r = await transaction(client => newPassword(client, Number(req.params.id), 10));
  if (!r) return res.status(404).json({ error: 'Ученик не найден' });
  res.json({ ok: true, ...r });
}));

app.delete('/api/students/:id', needAuth, needTeacher, asyncRoute(async (req, res) => {
  await db.query("delete from users where id=$1 and role='student'", [Number(req.params.id)]);
  res.json({ ok: true });
}));

app.post('/api/students/:id/password', needAuth, needTeacher, asyncRoute(async (req, res) => {
  const pass = String((req.body && req.body.password) || '');
  if (pass.length < 6) return res.status(400).json({ error: 'Пароль: минимум 6 символов' });
  const result = await db.query("update users set pass_hash=$1 where id=$2 and role='student'", [bcrypt.hashSync(pass, 10), Number(req.params.id)]);
  if (!result.rowCount) return res.status(404).json({ error: 'Ученик не найден' });
  res.json({ ok: true });
}));

app.put('/api/settings', needAuth, needTeacher, asyncRoute(async (req, res) => {
  const t = int(req.body && req.body.threshold, 0, 140);
  if (t === null) return res.status(400).json({ error: 'Порог: число от 0 до 140' });
  await db.query("insert into settings(key,value) values('threshold',$1) on conflict(key) do update set value=excluded.value", [String(t)]);
  res.json({ ok: true });
}));

app.use((error, req, res, next) => {
  console.error('Ошибка запроса:', error);
  if (res.headersSent) return next(error);
  res.status(500).json({ error: 'Внутренняя ошибка сервера' });
});

async function start() {
  await db.query(schema);
  const server = app.listen(PORT, () => console.log(`ЕНТ-трекер запущен на порту ${PORT}`));
  const shutdown = () => server.close(() => db.end());
  process.once('SIGINT', shutdown);
  process.once('SIGTERM', shutdown);
}

start().catch(async error => {
  console.error('Не удалось запустить приложение или подключиться к PostgreSQL:', error.message);
  await db.end();
  process.exitCode = 1;
});
